"""Pre-call caller context — this lead's own record, said in its own words.

`crm_program_context` (see `app.services.program_context`) carries facts about
the *programme*, read from the knowledge base. This module carries facts about
the *caller*: what they submitted, which stage they are in, when the enquiry
arrived. One compact string, assembled per call, stored nowhere.

Why it exists at all, when every one of those values is already in `user_data`
as a bare key: three things the agent cannot get from those keys.

**Labels.** A bare key is the JSONB key, not the admin's label. A key a form
generated by running words together tells an agent nothing about what the
workspace meant by it. The field definitions are already loaded where this is
called, so the label is right there, and a line reads as a sentence.

**One statement instead of a dozen variables.** A prompt cannot enumerate keys
it does not know the names of, and no key name here is knowable in advance.

**The negative.** This is the real point. Nothing previously told the agent
what is *not* recorded, so "when did I enrol?" had no grounded answer to fall
back on and invention was the path of least resistance. A context that lists
the recorded facts and nothing else makes "I don't have an enrolment date
recorded here" the honest, available answer.

Two rules shape the content:

**No field is named in code.** Which fields exist is the workspace's business.
Exclusions are by *type* — a `PHONE` or `EMAIL` field is the caller's own
contact detail and no answer needs it — never by key, so a second phone field
an admin adds tomorrow is excluded for the same reason the first one is.

**Nothing is inferred.** `created_at` is when the CRM received the enquiry and
is labelled as exactly that. It is never presented as an application,
enrolment, selection or payment date: no such field exists in the verified
production payload, and relabelling a timestamp into one would be inventing
the very fact the caller is asking about.
"""

from __future__ import annotations

import datetime as dt
from collections.abc import Iterable, Mapping

from app.fields.rendering import _zone
from app.models.enums import LeadFieldType
from app.models.field import LeadField
from app.services.tally import UNRESOLVED_SUFFIX

__all__ = [
    "EXCLUDED_FIELD_TYPES",
    "MAX_CONTEXT_CHARS",
    "LeadContextBuilder",
]

#: Hard ceiling on the finished string, matching `program_context`. Bolna
#: documents no limit for a `user_data` value; this is deliberately modest so
#: one talkative free-text answer cannot bloat every LLM call of the
#: conversation.
MAX_CONTEXT_CHARS = 1500

#: Field *types* whose values never belong in the caller context. These are the
#: caller's own contact details: they already know them, no answer needs them,
#: and keeping them out keeps avoidable PII away from the model. Excluding by
#: type rather than by key is what makes this work for a workspace whose phone
#: field is called "Mobile" and for the second one it adds next year.
EXCLUDED_FIELD_TYPES: frozenset[LeadFieldType] = frozenset(
    {LeadFieldType.PHONE, LeadFieldType.EMAIL}
)

#: How the enquiry date is introduced. The wording is the safety rule, not a
#: formatting choice — see the module docstring.
ENQUIRY_LABEL = "Enquiry received"
STAGE_LABEL = "Stage"


class LeadContextBuilder:
    """Turns one lead's already-projected, already-rendered values into a string.

    Deliberately does no I/O: no session, no query, no network. Everything it
    needs is what `VoiceCallService.build_user_data` has already loaded, which
    is also what makes it testable with a plain dict.

    It is handed the *rendered* map — the output of `render_for_voice`, which is
    itself fed by `FieldProjectionService`. Both chokepoints therefore still
    apply unchanged: a field the caller's permission template does not grant
    View on never reaches this builder, and empty values are already gone.
    """

    def __init__(self, *, max_chars: int = MAX_CONTEXT_CHARS) -> None:
        self._max = max_chars

    def build(
        self,
        rendered_values: Mapping[str, str],
        fields: Iterable[LeadField],
        *,
        stage_name: str | None = None,
        timezone_name: str | None = None,
        created_at: dt.datetime | None = None,
    ) -> str:
        """The caller context, or `""` when there is nothing worth saying.

        `rendered_values` is `render_for_voice`'s output: speech-ready strings
        keyed by lead-field key, already View-filtered and already stripped of
        empties.
        """
        lines = [
            *self._field_lines(rendered_values, fields),
            *self._record_lines(stage_name, timezone_name, created_at),
        ]
        return self._fit(lines)

    # --- the lead's own fields ---------------------------------------------

    def _field_lines(
        self, rendered_values: Mapping[str, str], fields: Iterable[LeadField]
    ) -> list[str]:
        """One `label: value` line per includable field, in the admin's order.

        `fields` arrives ordered by `sort_order`, which is the order the
        workspace chose for its own schema — so Name leads because the admin
        put it first, not because this code singles it out.
        """
        lines: list[str] = []
        for field in fields:
            if not self._includes(field):
                continue
            value = (rendered_values.get(field.key) or "").strip()
            if not value:
                continue
            lines.append(f"{field.label}: {value}")
        return lines

    @staticmethod
    def _includes(field: LeadField) -> bool:
        """Whether this field's value may be spoken back to the caller.

        A key carrying `UNRESOLVED_SUFFIX` cannot reach here in the first place
        — it has no field definition, so it is not in `fields` at all — but the
        check is explicit because that is the one key shape whose *value* is
        raw, unmapped form text (`app.services.tally`), and silence about why
        would invite someone to add it back.
        """
        if field.key.endswith(UNRESOLVED_SUFFIX):
            return False
        if field.field_type in EXCLUDED_FIELD_TYPES:
            return False
        # A field the admin hid from their own team is not something to read to
        # a caller. `user_data`'s bare keys still carry it; this layer does not.
        return not field.is_hidden

    # --- what the CRM itself records ---------------------------------------

    def _record_lines(
        self,
        stage_name: str | None,
        timezone_name: str | None,
        created_at: dt.datetime | None,
    ) -> list[str]:
        lines: list[str] = []
        stage = (stage_name or "").strip()
        if stage:
            lines.append(f"{STAGE_LABEL}: {stage}")
        if created_at is not None:
            # Architecture rule 10: the workspace's zone, not the server's and
            # not the browser's. `_zone` is shared with `render_for_voice` so
            # both say the same date for the same instant.
            moment = created_at
            if moment.tzinfo is None:
                moment = moment.replace(tzinfo=dt.UTC)
            local = moment.astimezone(_zone(timezone_name))
            lines.append(f"{ENQUIRY_LABEL}: {local.strftime('%d %B %Y')}")
        return lines

    # --- the ceiling --------------------------------------------------------

    def _fit(self, lines: list[str]) -> str:
        """Join within the ceiling, dropping whole lines rather than cutting one.

        A half-line reads as a fact that stops mid-word, so lines that do not
        fit are dropped entirely and the ones kept stay intact. Only when the
        very first line is itself over the ceiling is it trimmed, and then on a
        word boundary — there is no shorter honest alternative to saying part of
        it.
        """
        kept: list[str] = []
        used = 0
        for line in lines:
            cost = len(line) + (1 if kept else 0)
            if used + cost > self._max:
                continue
            kept.append(line)
            used += cost

        if kept:
            return "\n".join(kept)
        if not lines:
            return ""
        head = lines[0][: self._max - 1]
        if " " in head:
            head = head.rsplit(" ", 1)[0]
        return head + "…"
